version: '3.7'

services:
  jasyncdebug:
    image: jasyncdebug
    container_name: jasyncdebug
    env_file: .env

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres: